### ISSUE TITLE
Clear staking modal inputs and close modal after successful tx

### ISSUE THREAD

**Issue by shrnkld** [PIVX-Labs/MyPIVXWallet#120]
After a user has successfully created a staking tx then it would be good UX to clear the form data and close the modal.

Currently, after a successful tx the form isn't cleared so even when the user has closed the modal manually, the previous tx amount is still shown.

Tested on build: https://bafybeiczefcdkgylfjcrqliaoemawvrzfydqrfo4h2ajn7j3aznppy7hfi.on.fleek.co

**Comment by JSKitty** [comment]
Resolved by d93f54c0d07f06e9e946b6404bff0381c7c096d9
