### ISSUE TITLE
PIVX not appearing in wallet

### ISSUE THREAD

**Issue by mteam88** [PIVX-Labs/MyPIVXWallet#14]
I sent PIVX to this wallet. I don't see it appearing after 24 hours. 
![Screenshot 2022-01-21 2 28 12 PM](https://user-images.githubusercontent.com/84196639/150588473-cb8e34c8-d81a-42c1-bd26-2cb99027371f.png)
This is the account that I transferred to.
![Screenshot 2022-01-21 2 30 02 PM](https://user-images.githubusercontent.com/84196639/150588677-9fe73933-fcb9-4c6f-a58f-6a7ae6f612d5.png)

How long does it usually take?

**Comment by JSKitty** [comment]
I just checked out the site, and it's actually loading fine on my end.

Could you hit "Ctrl + Shift + i", check out the "Console" and "Network" tabs for any loading-related errors? It may be an issue with connecting to our explorer servers to load your balances, some people's ISPs have "blocked" the connection in rare cases.

**Comment by JSKitty** [comment]
Worst case scenario: Not to worry! You can always recover / export your private keys from MPW by clicking "Pubkey QR" in the Dashboard, that will reveal your private key, which can be saved or imported into PIVX Core.
I would suggest this anyway, for backup purposes. 😄

**Comment by mteam88** [comment]
Thank you for your time. I think it is a case of ISP blocking. I want to import my wallet to PIVX core. I have version 3.1.1. I am not sure if I need another version or if this version will work. What are the necessary commands to do it? `./pivx-cli importprivkey` and then something else? I would like to use the cli version.

Thanks again.

**Comment by mteam88** [comment]
Also, I think a new feature to add a notification if network errors occur would be a good idea. It would help others figure out if the wallet is not loading balance for that reason.

**Comment by kyeno** [comment]
PIVX Version 3.X is long deprecated and most likely you are on forked chain now. You should update to current stable (5.4.0 as of today), remove ALL of your blockchain files except `wallet.dat` and let it resync from scratch.

**Comment by mteam88** [comment]
done. What commands do I run now?

**Comment by mteam88** [comment]
I have opened the qt gui version. It is now syncing the blockchain.

**Comment by mteam88** [comment]
Yes, definitely ISP blocking problem. Got it working on another device.
