### ISSUE TITLE
[Request] No Network Connection Notification

### ISSUE THREAD

**Issue by mteam88** [PIVX-Labs/MyPIVXWallet#15]
Also, I think a new feature to add a notification if network errors occur would be a good idea. It would help others figure out if the wallet is not loading balance for that reason.

_Originally posted by @mteam88 in https://github.com/PIVX-Labs/MyPIVXWallet/issues/14#issuecomment-1019294452_

**Comment by Luke-Larsen** [comment]
[Pull request](https://github.com/PIVX-Labs/MyPIVXWallet/pull/20)
