### ISSUE TITLE
[Request] Add Hardware Wallet support

### ISSUE THREAD

**Issue by delandiaz** [PIVX-Labs/MyPIVXWallet#19]
Feature request to support Ledger/Trezor hardware wallets.

**Comment by Yuxanju** [comment]
You will have to synchronize your wallet and debug it

**Comment by Yuxanju** [comment]
This is important

**Comment by JSKitty** [comment]
:moneybag: Bounty added!

:wrench: **For developers:** The tag says `~270 PIV` but *do* remember that this is a **minimum** reward amount, a Hardware Wallet integration (e.g: Ledger connector) would absolutely warrant a 1,000+ PIV reward. :smile:

Thanks for this suggestion, highly appreciated! @delandiaz

:warning: And @Yuxanju... Your sub-comments make no sense in this context, and given your lack of GitHub history, I'd advise you to refrain from this repo for our users' safety.

**Comment by JSKitty** [comment]
Currently assigned to @Shangaman! 💰
