### ISSUE TITLE
Switching networks is buggy

### ISSUE THREAD

**Issue by Duddino** [PIVX-Labs/MyPIVXWallet#202]
Switching networks frequently causes uncaught exceptions and buggy behavior. 
![image](https://github.com/PIVX-Labs/MyPIVXWallet/assets/47313600/1b515f77-4e79-4e0d-8773-d8803537fdc3)
Additionally, the .getBlockCount() promise resolves even when the network is supposed to be destroyed

**Comment by panleone** [comment]
I think we should disable switching network on wallet loaded until we find a solution

**Comment by Duddino** [comment]
This was fixed by disabling the wallet deletion until wallet is synced
