### ISSUE TITLE
[Request] Add the basics of a 'Testnet Mode'

### ISSUE THREAD

**Issue by JSKitty** [PIVX-Labs/MyPIVXWallet#21]
MPW needs Testnet integration, and infrastructure has already been mostly provided by the Core Team to support such a mode, now we're needing the client-side work, here's a breakdown of some of the necessary work needed:

- Add Testnet constants to MPW (key prefixes, etc), MPW's current chainparams reside [here](https://github.com/PIVX-Labs/MyPIVXWallet/blob/355f19bcc227707e1e646835296ef6947a49479f/index.html#L55).
- Add a Setting toggle for 'Testnet Mode', which switches MPW to use the Testnet params.
- - Sub-requirement: Do **NOT** allow the user to switch **IF** they already have **ANY** wallet loaded.
- - Sub-requirement: Do **NOT** allow the user to encrypt **NOR** decrypt in Testnet mode, as encrypted keys are currently ambiguous.
- - Sub-requirement: Display 'Testnet Mode On' in the navbar if enabled, showing a distinct difference between the modes.

Currently, there is no complete server-side data provider setup for MPW on testnet, so this implementation is a bit of a 'chicken and egg' scenario as a developer will not have any means of testing TXs or Balances.

However if a developer completes the above tasks in this bounty, then I will take over the rest of the work and complete the integration at the provider-level, so don't worry too much about testing transactions or balances, I will do this work afterwards!

If any help is needed to complete this bounty, give me a shout in the [PIVX Labs Discord](https://discord.gg/v57eCP4MMx) and I'll help out!

**Comment by DeanSparrow** [comment]
I have added this and the "QR scan function" to my to-do list. This will be added after multi-langauge support is implemented.
