### ISSUE TITLE
Ordering on Transaction History incorrect

### ISSUE THREAD

**Issue by BillyTheBadOne** [PIVX-Labs/MyPIVXWallet#242]
On the way buying a PIVCard, if you get refunded, because of for example the service is not running correctly, the order in the History below the Wallet on the Dashboard shows the incorrect order.

![image](https://github.com/PIVX-Labs/MyPIVXWallet/assets/127999166/e4a71075-5729-431f-b7a3-93663500be5b)
The marked transactions show correct on the screenshot, but this was **after** I reloaded the page.
The Automatic update of the Information in the table initially sorted them the other way around.

**Comment by panleone** [comment]
This issue is likely already solved on the current master

**Comment by Duddino** [comment]
Closing this as I've not received any reports of this and is likely fixed. Feel free to reopen if you encounter the issue again
