### ISSUE TITLE
Governance Tab should display FIAT values in the common currency for the language chosen

### ISSUE THREAD

**Issue by BillyTheBadOne** [PIVX-Labs/MyPIVXWallet#250]
I'd like to see the Governance Tab to display the FIAT values in the common currency chosen by the language displayed.
As an example:
If the displayed language is german, or spanish, or alike, then the currency should be display in EUR (€) by default.

**Comment by Duddino** [comment]
Instead of making it based on the language, I based it off the current locale. This is because some languages may have different currencies and also to support languages that may have not been translated yet
