### ISSUE TITLE
Can't make second transaction without refresh

### ISSUE THREAD

**Issue by PalmTreeVI** [PIVX-Labs/MyPIVXWallet#3]
Once a transaction is sent, there is now way to get back to make another transaction.  Going to dashboard and back to create a new transaction still shows previous transaction success details.  Only way to clear if browser refresh/reload.

![Screenshot_2021-02-22_19-14-44](https://user-images.githubusercontent.com/64500998/108787396-a49ddd80-7543-11eb-8398-fa10428c4502.png)

After refresh, the previous details are still filled in from previous tx.

![Screenshot_2021-02-22_19-23-37](https://user-images.githubusercontent.com/64500998/108787400-a7003780-7543-11eb-8dfa-bbbe113acf3d.png)

**Comment by JSKitty** [comment]
Done, I've added a couple UI / UX improvements to the Sending page as it was quite clunky before, it'll display a bit nicer now, and you can also click "Continue" to close the 'TX Status' and be able to send additional TXs.
