### ISSUE TITLE
Shieleded address as refund address for piv cards?

### ISSUE THREAD

**Issue by borris345** [PIVX-Labs/MyPIVXWallet#333]
Is this possible? Doesn't work currently

**Comment by JSKitty** [comment]
PIVCards uses PIVX Core as it's payment processing backend (not MyPIVXWallet, so not relevant to this repository), unfortunately PIVX Core lacks the features needed to implement SHIELD Refund Addresses to PIVCards, PIVCards relies on raw UTXO management, which PIVX Core doesn't expose for SHIELD I believe.

It would likely require a complex rewrite of how PIVCards runs accounting, or a small-ish rewrite with the cost overhead of an additional SHIELD-only daemon to process SHIELD Txs.

**Comment by borris345** [comment]
The cost of privacy for that extra transaction.  I'd say worth it

**Comment by JSKitty** [comment]
I'll likely implement it using the dual-server proxy method and slightly bump our server proposal for it, but it'd be much easier on our infrastructure if PIVX Core just supported spending individual SHIELD notes in a raw fashion, may create a PIVX Core issue requesting it, it would half the costs of PIVCards maintenance and half the failure points for PIVCards.

Also to clarify: even with the dual-server model, PIVCards can't use SHIELD addresses in orders themselves, this can only enable _SHIELD **refunds**_, PIVX Core is simply missing the features we need to implement that with our payments system, we need a SHIELD-equivalent of `createrawtransaction`.

**Comment by JSKitty** [comment]
Quick update on this: talked with Fuzzbawls and actually we may be able to pull this off better than I thought, there are alternative RPCs (with some minor functionality differences) that should in theory allow us to change PIVCards fully to SHIELD (Order payments and Refund Addresses), we'll experiment with a full SHIELD-only implementation next week and see what we can do.

**Comment by JSKitty** [comment]
Closing, as PIVCards has implemented this thread 🚀
