### ISSUE TITLE
Add support for Ledger cold staking

### ISSUE THREAD

**Issue by Duddino** [PIVX-Labs/MyPIVXWallet#34]
Currently trying to cold stake PIVs on the ledger will fail, because, for security reasons, the pivx app (which is closely related to the btc one) only supports regular output scripts. 
For reference, this is what a regular output script looks like `OP_DUP OP_HASH160 c6b14278f4e37346889d7e0ccbea459e4b64c0ae OP_EQUALVERIFY OP_CHECKSIG` and this a coldstake script `OP_DUP OP_HASH160 OP_ROT OP_IF OP_COLDSTAKEVERIFY b3be8567d0190c67ca4675a0019089c55fe695f9 OP_ELSE c6b14278f4e37346889d7e0ccbea459e4b64c0ae OP_ENDIF OP_EQUALVERIFY OP_CHECKSIG`.
In order to fix this, the ledger needs to:
1. Recognize cold stake scripts
2. Present the output to the user, making sure to convert the stake pubkey to the correct form (i.e. it needs to start with an S)
3. Make sure that the second key, in the example `c6b14278f4e37346889d7e0ccbea459e4b64c0ae` points to the correct address (or more likely present it to an user and make them accept/refuse).

Currently the pivx app is in https://github.com/LedgerHQ/app-bitcoin, and needs to be compiled with the environment variable COIN=pivx. However, I'm not sure if approving these transactions goes outside of the scope of the app, I would recommend discussing it with a ledger developer first.

**Comment by panleone** [comment]
In my opinion this issue can be closed, what we need is a pivx app on ledger which is a much harder work

**Comment by panleone** [comment]
> @Duddino @panleone @JSKitty
> 
> Is this issue still closed, or can we revisit Ledger support? For those wanting to secure their keys away from personal computing devices, hardware/cold wallet support seems like a crucial feature. Privacy and security go hand-in-hand. Without security best practices (cold wallets), privacy is compromised.

This feature is in my priority list, will probably begin working on it when I finish with Shield Staking, I suggested to "close" only because it requires writing a ledger app for PIVX  (which is a difficult task compared to how it has been described here)

**Comment by panleone** [comment]
> Good to hear. Quick question: what is considered the most secure way to secure keys for staking on MPW? I generally don't like the idea of inputting keys from my semi-secure computer into a semi-secure browser.
> 
The most secure way would surely be using a ledger since all private keys remain in the hardware wallet

>Other than the sites listed below, are there any better reference material or documentation on how to write apps for Ledger? I do know they updated the PIVX code on their device as recently as about a few months ago.
>

the problem of the current app is that it's the same of bitcoin so we will never get features like shielding and cold staking unless we create our app. Maybe there is more development documentation here https://developers.ledger.com/

**Comment by Duddino** [comment]
Closing as not relevant to MPW
