### ISSUE TITLE
Add support for testnet addresses starting with x

### ISSUE THREAD

**Issue by Duddino** [PIVX-Labs/MyPIVXWallet#37]
Testnet addresses can start with `x` as well as `y`.
Should probably change [this](https://github.com/PIVX-Labs/MyPIVXWallet/blob/3589c18d6c54d499fc1be5c468d2f7066b505402/index.html#L77) to an array, and adapt the code accordingly

**Comment by JSKitty** [comment]
I wonder how we'll handle this; do we simply choose the `x/y` prefix at random during key generation? Adding support for the extra character is fine, just not sure how we practically apply it.

Small bounty added!

**Comment by Duddino** [comment]
I haven't dived into the code, but I think key generation works fine
