### ISSUE TITLE
Mobile Hamburger Menu Visibility

### ISSUE THREAD

**Issue by PalmTreeVI** [PIVX-Labs/MyPIVXWallet#5]
On dim mobile screens, the hamburger menu is barely noticeable/visible.
![Screenshot_2021-02-27_06-48-36](https://user-images.githubusercontent.com/64500998/109386370-4cab0200-78c8-11eb-98be-73c9c26ffb71.png)

**Comment by PalmTreeVI** [comment]
Here is solution if you desire:

```<nav class="navbar navbar-expand-lg sticky-top navbar-dark navbarSpecial">```
![Screenshot_2021-08-12_17-23-34](https://user-images.githubusercontent.com/64500998/129272011-86c0ea8b-d6e3-4bf7-a3a5-833fc0378a7a.png)

**Comment by JSKitty** [comment]
Applied this fix in https://github.com/PIVX-Labs/MyPIVXWallet/commit/6a0af49c32f8c520cbee7e934006e0b56d3e03d1, thank you again for the testing and suggestions!
