### ISSUE TITLE
Shielded support

### ISSUE THREAD

**Issue by panleone** [PIVX-Labs/MyPIVXWallet#54]
Currently MPW doesn't support shielded addresses/transactions, adding them is not easy so I suggest dividing the work in sub-tasks each one with a corresponding bounty:
- Add support for Zip32 (i.e shielded hierarchical deterministic wallet). This task in particular includes showing the correct balance for each address in the wallet and, due to the nature of shielded transactions, this will require saving all the note commitments/ nullifiers on the MPW client;
- Implement the possibility to create shielded transactions;
- Implement the conversion between transparent PIVs and shielded (and viceversa).

**Comment by panleone** [comment]
I am currently working on the first task, if you want to help write here/ on discord and I will assign

**Comment by Duddino** [comment]
> Implement the conversion between transparent PIVs and shielded (and viceversa).
Isn't that the same as shielded transactions? (Genuine question)

**Comment by panleone** [comment]
> > Implement the conversion between transparent PIVs and shielded (and viceversa).
> 
> Isn't that the same (or at least similar enough) as shielded transactions? (Genuine question)

yes it should be quite different, anyways that was just a possible proposal, if you have a better idea we can change the subtasks
