### ISSUE TITLE
Very long transactions don't get sent

### ISSUE THREAD

**Issue by Duddino** [PIVX-Labs/MyPIVXWallet#56]
I think that GET requests have a limit to how big they can be, according to [stackoverflow](https://stackoverflow.com/questions/2659952/maximum-length-of-http-get-request). There are a few ways we could tackle the issue:
- Break the tx into smaller ones
- Switch to POST requests for sending, which according to stackoverflow usually can handle a few GBs of data
- Ask our explorer hosts to increase the limit

**Comment by Duddino** [comment]
![image](https://user-images.githubusercontent.com/47313600/203427448-33afe587-e36a-44c9-874c-196b3ffff060.png)
This is the error i'm getting, `curl` doesn't sent it either

**Comment by JSKitty** [comment]
I think it's perfectly fine to switch `sendtx` to POST, Blockbook supports this natively luckily:
`POST /api/v1/sendtx/ (hex tx data in request body)`

Over time MPW will need to handle more complex transactions anyway, so it's good to raise this limit early.

**Comment by Duddino** [comment]
Alright gonna push some code in a bit then
