### ISSUE TITLE
SUGGESTION: Create Transaction Page

### ISSUE THREAD

**Issue by PalmTreeVI** [PIVX-Labs/MyPIVXWallet#6]
Save a click or tap!

When choosing "Create Transaction" menu item, perhaps the Simple Transaction form should be expanded without needing to select it (assuming that's where most people will inevitably go)

**Comment by JSKitty** [comment]
Implemented this suggestion, thanks alot @PalmTreeVI, been very busy for some months so I haven't been on this much!
